# Generated by Django 3.2.25 on 2024-11-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Cliente_ID', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField(help_text='Edad del cliente.')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], help_text='Género del cliente (Masculino, Femenino).', max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo promedio en la cuenta.', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Estado de actividad del cliente (1: Activo, 0: Inactivo).')),
                ('nivel_de_satisfaccion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Nivel de satisfacción del cliente en una escala del 1 al 5.')),
            ],
        ),
    ]
