# Generated by Django 3.2.25 on 2024-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nivel_de_satisfaccion',
            field=models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')]),
        ),
    ]
