# Generated by Django 3.2.25 on 2024-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosClientes', '0003_auto_20241127_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_id',
            field=models.CharField(default=213, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
